[tool.poetry]
name = "your-daily-dose-malware"
version = "0.2.0"
description = "Downloads and aggregates fresh malware samples collected from OSINT sources"
authors = ["Robert Thomas", "Prashant Shubham", "Mboula Penda Paul O’neal"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.2"
click = "^8.1.7"
python-dotenv = "^1.0.1"
rich = "^13.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
