[tool.poetry]
name = "your-daily-dose-malware"
version = "0.2.0"
description = "Downloads and aggregates fresh malware samples collected from OSINT sources"
authors = ["Robert Thomas", "Prashant Shubham", "Mboula Penda Paul O’neal"]
readme = "README.md"


[tool.poetry.scripts]
dd-run = "your_daily_dose_malware.commands:app"



[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.2"
python-dotenv = "^1.0.1"
rich = "^13.7.1"
typer = "^0.12.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 95